version: '3'

services:
  translation:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    environment:
      - E_TRANSLATION={"user":"translation_user","application":"translation_app","password":"translation_password","e_translation_url":"https://webgate.ec.europa.eu/etranslation/si/translate","callback_url":"https://localhost","simultanous_translations":5}
      - DATABASE={"jdbc_driver":"org.postgresql.Driver","jdbc_url":"jdbc:postgresql://postgres:5432/postgres","jdbc_max_pool_size":100,"user":"postgres","password":"","sql_queries":"doc/db-queries.properties"}
      - TRANSLATION_SERVICE={"port":8080}

  postgres:
    image: postgres:latest
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    command: postgres -c max_connections=1000 -c shared_buffers=2GB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=postgres
    restart: always
